# Generated by Django 5.1.3 on 2024-11-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_pets_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Unnamed', max_length=30),
        ),
        migrations.AddField(
            model_name='pet',
            name='personal_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
